[tool.poetry]
name = "exercise"
version = "0.1.0"
description = ""
authors = ["Piotr Tutak <ptutak@sii.pl>"]

[tool.poetry.dependencies]
python = "^3.9"
Cerberus = "^1.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
